Refactor to cache build products

diff --git a/.github/workflows/AsteriskCherryPickTest.yml b/.github/workflows/AsteriskCherryPickTest.yml
--- a/.github/workflows/AsteriskCherryPickTest.yml
+++ b/.github/workflows/AsteriskCherryPickTest.yml
@@ -7,22 +7,20 @@ on:
 
 env:
   PR_NUMBER: ${{ github.event.number }}
-  VAR_CHERRY_PICK_TEST_LABEL: ${{vars.CHERRY_PICK_TEST_LABEL}}
 
 jobs:
-  IdentifyBranches:
-    name: IdentifyBranches
+  GetBranches:
+    name: GetBranches
     runs-on: ubuntu-latest
     outputs:
-      branches:     ${{ steps.getbranches.outputs.branches }}
-      branch_count: ${{ steps.getbranches.outputs.branch_count }}
+      branches:           ${{ steps.getbranches.outputs.branches }}
+      branch_count:       ${{ steps.getbranches.outputs.branch_count }}
       testsuite_test_pr:  ${{ steps.testsuitepr.outputs.testsuite_test_pr }}
     steps:
       - name: Remove Trigger Label, Add InProgress Label
         env:
           GH_TOKEN: ${{ secrets.TOKEN }}
         run: |
-          echo "VCPTL: $VAR_CHERRY_PICK_TEST_LABEL"
           gh pr edit --repo ${{github.repository}} \
             --remove-label ${{vars.CHERRY_PICK_TEST_LABEL}} \
             --remove-label ${{vars.CHERRY_PICK_CHECKS_PASSED_LABEL}} \
@@ -30,16 +28,16 @@ jobs:
             --remove-label ${{vars.CHERRY_PICK_GATES_PASSED_LABEL}} \
             --remove-label ${{vars.CHERRY_PICK_GATES_FAILED_LABEL}} \
             --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
-            ${{env.PR_NUMBER}} || :
+            $PR_NUMBER || :
 
       - name: Get cherry-pick branches
         uses: asterisk/asterisk-ci-actions/GetCherryPickBranchesFromPR@main
         id: getbranches
         with:
-          repo:                    ${{github.repository}}
-          pr_number:               ${{env.PR_NUMBER}}
-          cherry_pick_regex:       ${{vars.CHERRY_PICK_REGEX}}
-          github_token:            ${{ secrets.TOKEN }}
+          repo:              ${{github.repository}}
+          pr_number:         ${{env.PR_NUMBER}}
+          cherry_pick_regex: ${{vars.CHERRY_PICK_REGEX}}
+          github_token:      ${{ secrets.TOKEN }}
 
       - name: Check Branch Count
         if: ${{ steps.getbranches.outputs.branch_count > 0 }}
@@ -48,25 +46,39 @@ jobs:
         run: |
           gh pr edit --repo ${{github.repository}} \
           --add-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
-          ${{env.PR_NUMBER}} || :
+          $PR_NUMBER || :
 
       - name: GetTestsuitePR
         id: testsuitepr
         uses: asterisk/asterisk-ci-actions/GetTestsuitePRFromAsteriskPR@main
         with:
-          repo:     ${{github.repository}}
-          pr_number: ${{github.event.number}}
-          testsuite_test_pr_regex: ${{ vars.TESTSUITE_TEST_PR_REGEX }}
+          repo:                            ${{github.repository}}
+          pr_number:                       ${{github.event.number}}
+          testsuite_test_pr_regex:         ${{ vars.TESTSUITE_TEST_PR_REGEX }}
           testsuite_test_auto_merge_regex: ${{ vars.TESTSUITE_TEST_AUTO_MERGE_REGEX }}
-          github_token: ${{ secrets.TOKEN }}
+          github_token:                    ${{ secrets.TOKEN }}
 
-  CherryPickTestMatrix:
-    needs: IdentifyBranches
-    if: ${{ needs.IdentifyBranches.outputs.branch_count > 0 && ( success() || failure() ) }}
+  CherryPickPrelimTestMatrix:
+    needs: GetBranches
+    if: ${{ needs.GetBranches.outputs.branch_count > 0 && ( success() || failure() ) }}
     strategy:
       fail-fast: false
       matrix:
-        branch: ${{ fromJSON(needs.IdentifyBranches.outputs.branches) }}
+        branch: ${{ fromJSON(needs.GetBranches.outputs.branches) }}
+    uses: ./.github/workflows/RunCherryPickPrelimTest.yml
+    with:
+      repo:        ${{github.repository}}
+      pr_number:   ${{github.event.number}}
+      base_branch: ${{matrix.branch}}
+    secrets: inherit
+
+  CherryPickTestMatrix:
+    needs: [GetBranches,CherryPickPrelimTestMatrix]
+    if: ${{ needs.GetBranches.outputs.branch_count > 0 && ( success() || failure() ) }}
+    strategy:
+      fail-fast: false
+      matrix:
+        branch: ${{ fromJSON(needs.GetBranches.outputs.branches) }}
     uses: ./.github/workflows/AsteriskUnitGateTest.yml
     with:
       test_type:         cherry-pick
@@ -77,44 +89,40 @@ jobs:
       build_options:     ${{vars.BUILD_OPTIONS}}
       unittest_command:  ${{vars.UNITTEST_COMMAND}}
       testsuite_repo:    ${{vars.TESTSUITE_REPO}}
-      testsuite_test_pr: ${{needs.IdentifyBranches.outputs.testsuite_test_pr}}
+      testsuite_test_pr: ${{needs.GetBranches.outputs.testsuite_test_pr}}
       gatetest_list:     ${{vars.GATETEST_LIST}}
       gatetest_commands: ${{vars.GATETEST_COMMANDS}}
     secrets: inherit
 
   CherryPickTestResults:
-    needs: [ IdentifyBranches, CherryPickTestMatrix ]
-    if: ${{ needs.IdentifyBranches.outputs.branch_count > 0 && ( success() || failure() ) }}
+    needs: [ GetBranches, CherryPickPrelimTestMatrix, CherryPickTestMatrix ]
+    if: ${{ needs.GetBranches.outputs.branch_count > 0 && ( success() || failure() ) }}
     runs-on: ubuntu-latest
     steps:
       - name: Check test matrix status
         env:
-          RESULT:    ${{needs.CherryPickTestMatrix.result}}
-          GH_TOKEN:  ${{ secrets.TOKEN }}
+          RESULT_UNIT:       ${{needs.CherryPickTestMatrix.result}}
+          GH_TOKEN:          ${{ secrets.TOKEN }}
+          IN_PROGRESS_LABEL: ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}}
+          PASSED_LABEL:      ${{vars.CHERRY_PICK_CHECKS_PASSED_LABEL}}
+          FAILED_LABEL:      ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}}
         run: |
-          case $RESULT in
+          declare -i rc=0
+          case $RESULT_UNIT in
             success)
-              gh pr edit --repo ${{github.repository}} \
-                --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
-                --add-label ${{vars.CHERRY_PICK_CHECKS_PASSED_LABEL}} \
-                ${{env.PR_NUMBER}} || :
-              echo "::notice::All tests passed"
-              exit 0
+              echo "All tests passed"
               ;;
             skipped)
-              gh pr edit --repo ${{github.repository}} \
-                --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
-                --add-label ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}} \
-                ${{env.PR_NUMBER}} || :
-              echo "::notice::Unit tests were skipped because of an earlier failure"
-              exit 1
+              echo "One or more tests were skipped because of an earlier failure"
+              rc+=1
               ;;
             *)
-              gh pr edit --repo ${{github.repository}} \
-                --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
-                --add-label ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}} \
-                ${{env.PR_NUMBER}} || :
-              echo "::error::One or more tests failed ($RESULT)"
-              exit 1
+              echo "One or more tests failed ($RESULT)"
+              rc+=1
           esac
-
+          [ $rc -gt 0 ] && label=$FAILED_LABEL || label=$PASSED_LABEL
+          gh pr edit --repo ${{github.repository}} \
+            --remove-label $IN_PROGRESS_LABEL \
+            --add-label $label \
+            $PR_NUMBER || :
+          exit $rc
diff --git a/.github/workflows/AsteriskMergePR.yml b/.github/workflows/AsteriskMergePR.yml
--- a/.github/workflows/AsteriskMergePR.yml
+++ b/.github/workflows/AsteriskMergePR.yml
@@ -14,12 +14,12 @@ on:
         required: true
 
 env:
-  PR_NUMBER: ${{ github.event.number }}
+  PR_NUMBER:   ${{ github.event.number }}
   BASE_BRANCH: ${{github.event.pull_request.base.ref}}
 
 jobs:
-  IdentifyBranches:
-    name: IdentifyBranches
+  GetBranches:
+    name: GetBranches
     runs-on: ubuntu-latest
     outputs:
       branches:     ${{ steps.getbranches.outputs.branches }}
@@ -28,14 +28,12 @@ jobs:
     steps:
       - name: Clean up labels
         env:
-          GH_TOKEN:          ${{ secrets.TOKEN }}
+          GH_TOKEN: ${{ secrets.TOKEN }}
         run: |
           gh pr edit --repo ${{github.repository}} \
             --remove-label ${{github.event.label.name}} \
             --remove-label ${{vars.PRE_MERGE_CHECKS_PASSED_LABEL}} \
             --remove-label ${{vars.PRE_MERGE_CHECKS_FAILED_LABEL}} \
-            --remove-label ${{vars.PRE_MERGE_GATES_PASSED_LABEL}} \
-            --remove-label ${{vars.PRE_MERGE_GATES_FAILED_LABEL}} \
             --remove-label ${{vars.PRE_MERGE_TESTING_IN_PROGRESS}} \
             ${{env.PR_NUMBER}} || :
 
@@ -43,17 +41,17 @@ jobs:
         uses: asterisk/asterisk-ci-actions/GetCherryPickBranchesFromPR@main
         id: getbranches
         with:
-          repo:                    ${{github.repository}}
-          pr_number:               ${{env.PR_NUMBER}}
-          cherry_pick_regex:       ${{vars.CHERRY_PICK_REGEX}}
-          github_token:            ${{ secrets.TOKEN }}
+          repo:              ${{github.repository}}
+          pr_number:         ${{env.PR_NUMBER}}
+          cherry_pick_regex: ${{vars.CHERRY_PICK_REGEX}}
+          github_token:      ${{ secrets.TOKEN }}
 
       - name: Check Branch Count
         id: checkbranches
         env:
-          BRANCH_COUNT:  ${{ steps.getbranches.outputs.branch_count }}
-          BRANCHES:  ${{ steps.getbranches.outputs.branches }}
-          GH_TOKEN: ${{ secrets.TOKEN }}
+          BRANCH_COUNT: ${{ steps.getbranches.outputs.branch_count }}
+          BRANCHES:     ${{ steps.getbranches.outputs.branches }}
+          GH_TOKEN:     ${{ secrets.TOKEN }}
         run: |
           gh pr edit --repo ${{github.repository}} \
           --add-label ${{vars.PRE_MERGE_TESTING_IN_PROGRESS}} \
@@ -65,19 +63,19 @@ jobs:
         if: ${{ steps.getbranches.outputs.branch_count > 0 }}
         uses: asterisk/asterisk-ci-actions/CherryPick@main
         with:
-          repo:              ${{github.repository}}
-          pr_number:         ${{env.PR_NUMBER}}
-          branches:          ${{steps.getbranches.outputs.branches}}
-          github_token:      ${{secrets.TOKEN}}
-          push:              false
+          repo:         ${{github.repository}}
+          pr_number:    ${{env.PR_NUMBER}}
+          branches:     ${{steps.getbranches.outputs.branches}}
+          github_token: ${{secrets.TOKEN}}
+          push:         false
 
-  PreMergeUnitTestMatrix:
-    needs: [ IdentifyBranches ]
+  PreMergeTest:
+    needs: [ GetBranches ]
     if: success()
     strategy:
       fail-fast: false
       matrix:
-        branch: ${{ fromJSON(needs.IdentifyBranches.outputs.all_branches) }}
+        branch: ${{ fromJSON(needs.GetBranches.outputs.all_branches) }}
     uses: ./.github/workflows/AsteriskUnitGateTest.yml
     with:
       test_type:         cherry-pick
@@ -95,42 +93,37 @@ jobs:
 
   PreMergeTestResults:
     if: always()
-    needs: [ IdentifyBranches, PreMergeUnitTestMatrix ]
+    needs: [ GetBranches, PreMergeTest ]
     runs-on: ubuntu-latest
     steps:
       - name: Check unit test matrix status
         env:
-          RESULT:    ${{needs.PreMergeUnitTestMatrix.result}}
-          GH_TOKEN:  ${{ secrets.TOKEN }}
+          RESULT:   ${{needs.PreMergeUnitTestMatrix.result}}
+          GH_TOKEN: ${{ secrets.TOKEN }}
         run: |
+          declare -i rc=0
           case $RESULT in
             success)
-              gh pr edit --repo ${{github.repository}} \
-                --remove-label ${{vars.PRE_MERGE_TESTING_IN_PROGRESS}} \
-                --add-label ${{vars.PRE_MERGE_CHECKS_PASSED_LABEL}} \
-                ${{env.PR_NUMBER}} || :
-              echo "::notice::All tests passed"
-              exit 0
+              echo "All tests passed"
               ;;
             skipped)
-              gh pr edit --repo ${{github.repository}} \
-                --remove-label ${{vars.PRE_MERGE_TESTING_IN_PROGRESS}} \
-                --add-label ${{vars.PRE_MERGE_CHECKS_FAILED_LABEL}} \
-                ${{env.PR_NUMBER}} || :
-              echo "::notice::Unit tests were skipped because of an earlier failure"
-              exit 1
+              echo "One or more tests were skipped because of an earlier failure"
+              rc+=1
               ;;
             *)
-              gh pr edit --repo ${{github.repository}} \
-                --remove-label ${{vars.PRE_MERGE_TESTING_IN_PROGRESS}} \
-                --add-label ${{vars.PRE_MERGE_CHECKS_FAILED_LABEL}} \
-                ${{env.PR_NUMBER}} || :
-              echo "::error::One or more tests failed ($RESULT)"
-              exit 1
+              echo "One or more tests failed ($RESULT)"
+              rc+=1
+              ;;
           esac
+          [ $rc -gt 0 ] && label=${{vars.PRE_MERGE_CHECKS_FAILED_LABEL}} || \
+            label=${{vars.PRE_MERGE_CHECKS_PASSED_LABEL}}
+          gh pr edit --repo ${{github.repository}} \
+            --remove-label ${{vars.PRE_MERGE_TESTING_IN_PROGRESS}} \
+            --add-label $label \
+            $PR_NUMBER || :
 
   MergeAndCherryPick:
-    needs: [ IdentifyBranches, PreMergeTestResults ]
+    needs: [ GetBranches, PreMergeTestResults ]
     if: success() && !inputs.dry_run
     runs-on: ubuntu-latest
     steps:
@@ -140,48 +133,48 @@ jobs:
         run: |
             gh pr edit --repo ${{github.repository}} \
               --add-label ${{vars.MERGE_IN_PROGRESS_LABEL}} \
-              ${{env.PR_NUMBER}} || :
+              $PR_NUMBER || :
 
       - name: Get Token needed to push cherry-picks
         id: get_workflow_token
         uses: peter-murray/workflow-application-token-action@v3
         with:
-          application_id: ${{secrets.application_id}}
+          application_id:          ${{secrets.application_id}}
           application_private_key: ${{secrets.application_private_key}}
-          organization: asterisk
+          organization:            asterisk
 
-      - name: Merge and Cherry Pick to ${{needs.IdentifyBranches.outputs.branches}}
+      - name: Merge and Cherry Pick to ${{needs.GetBranches.outputs.branches}}
         id: mergecp
         uses: asterisk/asterisk-ci-actions/MergeAndCherryPickComposite@main
         with:
           repo:          ${{github.repository}}
           pr_number:     ${{env.PR_NUMBER}}
-          branches:      ${{needs.IdentifyBranches.outputs.branches}}
+          branches:      ${{needs.GetBranches.outputs.branches}}
           force:         ${{env.FORCE}}
           github_token:  ${{steps.get_workflow_token.outputs.token}}
 
       - name: Merge Cleanup
         if: always()
         env:
-          RESULT:    ${{ steps.mergecp.outcome }}
-          GH_TOKEN:  ${{ secrets.TOKEN }}
-          BRANCH_COUNT: ${{ needs.IdentifyBranches.outputs.branch_count }}
-          BRANCHES:     ${{ needs.IdentifyBranches.outputs.branches }}
+          RESULT:       ${{ steps.mergecp.outcome }}
+          GH_TOKEN:     ${{ secrets.TOKEN }}
+          BRANCH_COUNT: ${{ needs.GetBranches.outputs.branch_count }}
+          BRANCHES:     ${{ needs.GetBranches.outputs.branches }}
 
         run: |
           case $RESULT in
             success)
               gh pr edit --repo ${{github.repository}} \
                 --remove-label ${{vars.MERGE_IN_PROGRESS_LABEL}} \
-                ${{env.PR_NUMBER}} || :
+                $PR_NUMBER || :
               if [ $BRANCH_COUNT -eq 0 ] ; then
                 gh pr comment --repo ${{github.repository}} \
                   -b "Successfully merged to branch $BASE_BRANCH." \
-                  ${{env.PR_NUMBER}} || :
+                  $PR_NUMBER || :
               else
                 gh pr comment --repo ${{github.repository}} \
                   -b "Successfully merged to branch $BASE_BRANCH and cherry-picked to $BRANCHES" \
-                  ${{env.PR_NUMBER}} || :
+                  $PR_NUMBER || :
               fi
               exit 0
               ;;
@@ -189,7 +182,7 @@ jobs:
               gh pr edit --repo ${{github.repository}} \
                 --remove-label ${{vars.MERGE_IN_PROGRESS_LABEL}} \
                 --add-label ${{vars.MERGE_FAILED_LABEL}} \
-                ${{env.PR_NUMBER}} || :
+                $PR_NUMBER || :
               exit 1
               ;;
               *)
diff --git a/.github/workflows/AsteriskRecheckPR.yml b/.github/workflows/AsteriskRecheckPR.yml
--- a/.github/workflows/AsteriskRecheckPR.yml
+++ b/.github/workflows/AsteriskRecheckPR.yml
@@ -7,18 +7,18 @@ on:
         required: true
 
 env:
-  PR_NUMBER: ${{ github.event.number }}
+  PR_NUMBER: ${{github.event.number}}
 
 jobs:
   Setup:
     runs-on: ubuntu-latest
     outputs:
-      testsuite_test_pr:  ${{ steps.testsuitepr.outputs.testsuite_test_pr }}
+      testsuite_test_pr:  ${{steps.testsuitepr.outputs.testsuite_test_pr}}
     steps:
       - name: Set Label
         id: setlabel
         env:
-          GH_TOKEN:  ${{ secrets.TOKEN }}
+          GH_TOKEN:  ${{secrets.TOKEN}}
         run: | 
           gh pr edit --repo ${{github.repository}} \
             --remove-label ${{vars.RECHECKPR_LABEL}} \
@@ -31,11 +31,11 @@ jobs:
         id: testsuitepr
         uses: asterisk/asterisk-ci-actions/GetTestsuitePRFromAsteriskPR@main
         with:
-          repo:     ${{github.repository}}
-          pr_number: ${{github.event.number}}
-          testsuite_test_pr_regex: ${{ vars.TESTSUITE_TEST_PR_REGEX }}
-          testsuite_test_auto_merge_regex: ${{ vars.TESTSUITE_TEST_AUTO_MERGE_REGEX }}
-          github_token: ${{ secrets.TOKEN }}
+          repo:                            ${{github.repository}}
+          pr_number:                       ${{github.event.number}}
+          testsuite_test_pr_regex:         ${{vars.TESTSUITE_TEST_PR_REGEX}}
+          testsuite_test_auto_merge_regex: ${{vars.TESTSUITE_TEST_AUTO_MERGE_REGEX}}
+          github_token:                    ${{secrets.TOKEN}}
 
   PRCheck:
     name: PRCheck
@@ -50,7 +50,7 @@ jobs:
       build_options:     ${{vars.BUILD_OPTIONS}}
       unittest_command:  ${{vars.UNITTEST_COMMAND}}
       testsuite_repo:    ${{vars.TESTSUITE_REPO}}
-      testsuite_test_pr: ${{ needs.Setup.outputs.testsuite_test_pr }}
+      testsuite_test_pr: ${{needs.Setup.outputs.testsuite_test_pr}}
       gatetest_list:     ${{vars.GATETEST_LIST}}
       gatetest_commands: ${{vars.GATETEST_COMMANDS}}
     secrets: inherit
@@ -62,32 +62,29 @@ jobs:
     steps:
       - name: Check status
         env:
-          GH_TOKEN:  ${{ secrets.TOKEN }}
-          RESULT_UNIT: ${{ needs.PRCheck.result }}
-          TESTS_PASSED: ${{ vars.PR_SUBMIT_TESTS_PASSED }}
-          TESTS_FAILED: ${{ vars.PR_SUBMIT_TESTS_FAILED }}
+          GH_TOKEN:          ${{secrets.TOKEN}}
+          RESULT_UNIT:       ${{needs.PRCheck.result}}
+          IN_PROGRESS_LABEL: ${{vars.PR_SUBMIT_TESTING_IN_PROGRESS}}
+          PASSED_LABEL:      ${{vars.PR_SUBMIT_TESTS_PASSED}}
+          FAILED_LABEL:      ${{vars.PR_SUBMIT_TESTS_FAILED}}
         run: |
           declare -i rc=0
-          echo "all results: ${{ toJSON(needs.*.result) }}"
           case $RESULT_UNIT in
             success)
-              echo "::notice::Unit/Gate tests passed"
+              echo "All tests passed"
               ;;
             skipped)
-              echo "::error::Unit/Gate tests were skipped because of an earlier failure"
+              echo "One or more tests were skipped because of an earlier failure"
               rc+=1
               ;;
             *)
-              echo "::error::One or more Unit/Gate tests failed ($RESULT_UNIT)"
+              echo "One or more tests failed ($RESULT)"
               rc+=1
           esac
-          
-          label=$TESTS_PASSED
-          if [ $rc != 0 ] ; then
-            label=$TESTS_FAILED
-          fi
+          [ $rc -gt 0 ] && label=$FAILED_LABEL || label=$PASSED_LABEL
           gh pr edit --repo ${{github.repository}} \
-            --remove-label ${{vars.PR_SUBMIT_TESTING_IN_PROGRESS}} \
+            --remove-label $IN_PROGRESS_LABEL \
             --add-label $label \
-              $PR_NUMBER || :
+            ${PR_NUMBER} || :
           exit $rc
+          
diff --git a/.github/workflows/AsteriskUnitGateTest.yml b/.github/workflows/AsteriskUnitGateTest.yml
--- a/.github/workflows/AsteriskUnitGateTest.yml
+++ b/.github/workflows/AsteriskUnitGateTest.yml
@@ -1,4 +1,4 @@
-name: AsteriskUnitGateTest
+name: UnitGateTest
 on:
   workflow_call:
     inputs:
@@ -27,8 +27,15 @@ on:
         required: false
         type: string
         default: ""
+      output_cache_dir:
+        required: false
+        type: string
+        default: cache
+      build_cache_dir:
+        required: false
+        type: string
+        default: build-cache
       modules_blacklist:
-        description: 'List of Asterisk modules to blacklist from the build'
         type: string
         default: ""
         required: false
@@ -41,7 +48,8 @@ on:
         default: Gate
       testsuite_repo:
         type: string
-        required: true
+        required: false
+        default: asterisk/testsuite
       testsuite_test_pr:
         type: string
         required: false
@@ -51,76 +59,102 @@ on:
       gatetest_commands:
         type: string
         required: true
+      user_group:
+        required: false
+        type: string
+        default: asteriskci:users
     secrets:
       TOKEN:
         required: true
-jobs:
 
-  UnitTests:
+jobs:
+  Build:
+    uses: ./.github/workflows/AsteriskBuildAndCache.yml
+    with:
+      test_type:         ${{inputs.test_type}}
+      asterisk_repo:     ${{inputs.asterisk_repo}}
+      pr_number:         ${{inputs.pr_number}}
+      base_branch:       ${{inputs.base_branch}}
+      is_cherry_pick:    ${{inputs.is_cherry_pick}}
+      build_options:     ${{inputs.build_options}}
+      modules_blacklist: ${{inputs.modules_blacklist}}
+      build_cache_dir:   ${{inputs.build_cache_dir}}
+      build_cache_key:   ${{github.workflow}}-${{inputs.pr_number}}-${{inputs.base_branch}}
+    secrets: inherit
+  
+  Unit:
+    needs: Build
     uses: ./.github/workflows/RunAsteriskUnitTests.yml
     with:
-      asterisk_repo:     ${{ inputs.asterisk_repo }}
-      pr_number:         ${{ inputs.pr_number }}
-      base_branch:       ${{ inputs.base_branch }}
-      is_cherry_pick:    ${{ inputs.is_cherry_pick }}
-      build_options:     ${{ inputs.build_options }}
-      unittest_command:  ${{ inputs.unittest_command }}
+      test_type:         ${{inputs.testsuite_test_type}}
+      base_branch:       ${{inputs.base_branch}}
+      user_group:        ${{inputs.user_group}}
+      unittest_command:  ${{inputs.unittest_command}}
+      output_cache_dir:  ${{inputs.output_cache_dir}}
+      build_cache_dir:   ${{inputs.build_cache_dir}}
+      build_cache_key:   ${{github.workflow}}-${{inputs.pr_number}}-${{inputs.base_branch}}
     secrets: inherit
 
-  GateTests:
-    if: ${{ inputs.testsuite_test_type != 'NONE' }}
+  Gate:
+    needs: Build
+    name: Gate
+    if: ${{inputs.testsuite_test_type != 'NONE' && inputs.gatetest_list != '[]'}}
     strategy:
       fail-fast: false
       matrix:
-        group: ${{ fromJSON(inputs.gatetest_list) }}
+        group: ${{fromJSON(inputs.gatetest_list)}}
     uses: ./.github/workflows/RunAsteriskGateTests.yml
     with:
-      test_type:         ${{ inputs.testsuite_test_type }}
-      asterisk_repo:     ${{ inputs.asterisk_repo }}
-      pr_number:         ${{ inputs.pr_number }}
-      base_branch:       ${{ inputs.base_branch }}
-      is_cherry_pick:    ${{ inputs.is_cherry_pick }}
-      testsuite_repo:    ${{ inputs.testsuite_repo }}
-      testsuite_test_pr: ${{ inputs.testsuite_test_pr }}
-      gatetest_group:    ${{ matrix.group }}
-      gatetest_commands: ${{ inputs.gatetest_commands }}
+      test_type:         ${{inputs.testsuite_test_type}}
+      base_branch:       ${{inputs.base_branch}}
+      user_group:        ${{inputs.user_group}}
+      testsuite_repo:    ${{inputs.testsuite_repo}}
+      testsuite_test_pr: ${{inputs.testsuite_test_pr}}
+      gatetest_group:    ${{matrix.group}}
+      gatetest_commands: ${{inputs.gatetest_commands}}
+      build_cache_dir:   ${{inputs.build_cache_dir}}
+      build_cache_key:   ${{github.workflow}}-${{inputs.pr_number}}-${{inputs.base_branch}}
     secrets: inherit
 
-  UnitGateTestResults:
+  Results:
+    name: '**Results-${{inputs.base_branch}}'
     if: always()
     runs-on: ubuntu-latest
-    needs: [UnitTests,GateTests]
+    needs: [Unit,Gate]
     steps:
       - name: Check test matrix status
         env:
-          GH_TOKEN:  ${{ secrets.TOKEN }}
-          PR_NUMBER: ${{ inputs.pr_number }}
-          RESULT_UNIT: ${{ needs.UnitTests.result }}
-          RESULT_GATE: ${{ needs.GateTests.result }}
+          GH_TOKEN:        ${{secrets.TOKEN}}
+          PR_NUMBER:       ${{inputs.pr_number}}
+          ASTERISK_REPO:   ${{inputs.asterisk_repo}}
+          RESULT_UNIT:     ${{needs.Unit.result}}
+          RESULT_GATE:     ${{needs.Gate.result}}
+          BUILD_CACHE_KEY: ${{github.workflow}}-${{inputs.pr_number}}-${{inputs.base_branch}}
         run: |
+          gh cache delete -R ${ASTERISK_REPO} ${BUILD_CACHE_KEY} || :
           declare -i rc=0
-          echo "all results: ${{ toJSON(needs.*.result) }}"
+          echo "all results: ${{toJSON(needs.*.result)}}"
           case $RESULT_UNIT in
             success)
-              echo "::notice::Unit tests passed"
+              echo "Unit tests passed"
               ;;
             skipped)
-              echo "::error::Unit tests were skipped because of an earlier failure"
+              echo "Unit tests were skipped because of an earlier failure"
               rc+=1
               ;;
             *)
-              echo "::error::One or more unit tests failed ($RESULT_UNIT)"
+              echo "One or more unit tests failed ($RESULT)"
               rc+=1
           esac
           case $RESULT_GATE in
             success)
-              echo "::notice::Gate tests passed"
+              echo "Gate tests passed"
               ;;
             skipped)
-              echo "::notice::Gate tests were not requested"
+              echo "Gate tests were not requested"
               ;;
             *)
-              echo "::error::One or more gate tests failed ($RESULT_GATE)"
+              echo "One or more gate tests failed ($RESULT)"
               rc+=1
           esac
           exit $rc
diff --git a/.github/workflows/RunAsteriskGateTests.yml b/.github/workflows/RunAsteriskGateTests.yml
--- a/.github/workflows/RunAsteriskGateTests.yml
+++ b/.github/workflows/RunAsteriskGateTests.yml
@@ -5,36 +5,13 @@ on:
       test_type:
         required: true
         type: string
-      asterisk_repo:
-        required: true
-        type: string
-      pr_number:
-        required: true
-        type: string
       base_branch:
         required: true
         type: string
-      is_cherry_pick:
-        required: false
-        type: boolean
-        default: false
-      build_script:
-        required: false
+      user_group:
         type: string
-        default: "buildAsterisk.sh"
-      build_options:
         required: false
-        type: string
-        default: ""
-      modules_blacklist:
-        description: 'List of Asterisk modules to blacklist from the build'
-        type: string
-        default: ""
-        required: false
-      cache_dir:
-        type: string
-        default: cache
-        required: false
+        default: asteriskci:users
       testsuite_repo:
         description: 'Testsuite Repo (default: asterisk/testsuite)'
         type: string
@@ -51,48 +28,92 @@ on:
         description: 'Gate Commands'
         type: string
         required: true
+      build_cache_dir:
+        type: string
+        required: false
+        default: build-cache
+      build_cache_key:
+        type: string
+        required: true
+
+env:
+  GH_TOKEN:     ${{secrets.TOKEN}}
+  GITHUB_TOKEN: ${{secrets.TOKEN}}
+  TEST_TYPE:    ${{inputs.test_type}}
+  BASE_BRANCH:  ${{inputs.base_branch}}
+  CACHE_DIR:    ${{inputs.output_cache_dir}}
+  USER_GROUP:   ${{inputs.user_group}}
+  ACTION_DIR:   asterisk-ci-actions
+  SCRIPT_DIR:   ${{github.workspace}}/asterisk-ci-actions/scripts
+  OUTPUT_DIR:   ${{github.workspace}}/${{inputs.output_cache_dir}}/output
+  REPO_DIR:     ${{github.event.repository.name}}
+  REPO_ORG:     ${{github.event.repository.owner.login}}
+  CI_BRANCH:    main-cache-builds
+
+  TESTSUITE_REPO:     ${{inputs.testsuite_repo}}
+  TESTSUITE_TEST_PR:  ${{inputs.testsuite_test_pr}}
+  GATETEST_GROUP:     ${{inputs.gatetest_group}}
+  GATETEST_COMMAND:   ${{toJSON(fromJSON(inputs.gatetest_commands)[inputs.gatetest_group])}}
 
 jobs:
   RunGateTests:
-    name: GateTests ${{ inputs.base_branch }} ${{inputs.gatetest_group}}
+    name: ${{ inputs.base_branch }} ${{inputs.gatetest_group}}
     runs-on: ubuntu-latest
-    steps:
-      - name: SetupUbuntuRunner
-        uses: asterisk/asterisk-ci-actions/SetupUbuntuRunner@main
-
-      - name: GetTestsuiteDir
+    container:
+      image: ghcr.io/asterisk/asteriskci-agent-rocky8:latest
+      options: --privileged
+    defaults:
+      run:
         shell: bash
+    steps:
+      - name: Restore Asterisk Cache
+        uses: asterisk/asterisk-ci-actions/RestoreAsteriskFromCache@main-cache-builds
+        with:
+          repo_dir:        ${{github.event.repository.name}}
+          build_cache_dir: ${{inputs.build_cache_dir}}
+          build_cache_key: ${{inputs.build_cache_key}}
+          user_group:      ${{inputs.user_group}}
+
+      - name: Setup
         run: |
-          echo "GC_TESTSUITE_DIR=$(basename ${{inputs.testsuite_repo}})" >> "${GITHUB_ENV}"
-          BASE_BRANCH="${{inputs.base_branch}}"
-          GC_TEST_NAME="${{inputs.test_type}}-${{inputs.gatetest_group}}-${BASE_BRANCH//\//-}"
-          echo "GC_TEST_NAME=${GC_TEST_NAME}" >> "${GITHUB_ENV}"
+          sysctl -w kernel.core_pattern=/tmp/core-%e-%t
+          chmod 1777 /tmp
+          echo "GC_TESTSUITE_DIR=$(basename ${TESTSUITE_REPO})" >> "${GITHUB_ENV}"
+          echo "GC_TEST_NAME=${TEST_TYPE}-${GATETEST_GROUP}-${BASE_BRANCH//\//-}" >> "${GITHUB_ENV}"
 
-      - name: Get Asterisk
-        uses: asterisk/asterisk-ci-actions/GetRepo@main
-        with:
-          repo:              ${{inputs.asterisk_repo}}
-          base_branch:       ${{inputs.base_branch}}
-          pr_number:         ${{inputs.pr_number}}
-          is_cherry_pick:    ${{inputs.is_cherry_pick}}
-          build_script:      ${{inputs.build_script}}
-          build_options:     ${{inputs.build_options}}
-          github_token:      ${{secrets.TOKEN}}
-          modules_blacklist: ${{inputs.modules_blacklist}}
+          echo "*** Cloning ${REPO_ORG}/${ACTION_DIR}"
+          git clone ${GITHUB_SERVER_URL}/${REPO_ORG}/${ACTION_DIR}
+          git -C ${ACTION_DIR} checkout ${CI_BRANCH:-main}
 
-      - id: runtests
-        name: ${{inputs.test_type}} Test ${{inputs.gatetest_group}}-${{inputs.base_branch}}
-        uses: asterisk/asterisk-ci-actions/RunAsteriskGateTests@main
-        with:
-          asterisk_repo:     ${{inputs.asterisk_repo}}
-          base_branch:       ${{inputs.base_branch}}
-          pr_number:         ${{inputs.pr_number}}
-          cache_dir:         ${{inputs.cache_dir}}
-          github_token:      ${{secrets.TOKEN}}
-          testsuite_repo:    ${{inputs.testsuite_repo}}
-          testsuite_test_pr: ${{inputs.testsuite_test_pr}}
-          gatetest_group:    0
-          gatetest_command:  ${{ toJSON(fromJSON(inputs.gatetest_commands)[inputs.gatetest_group]) }}
+      - name: ${{inputs.test_type}} Test ${{inputs.base_branch}}-${{inputs.gatetest_group}}
+        run: |
+          TESTSUITE_DIR=${GITHUB_WORKSPACE}/${GC_TESTSUITE_DIR}
+          mkdir -p ${TESTSUITE_DIR}
+          git clone --depth 1 --no-tags -q -b ${BASE_BRANCH} \
+          	${GITHUB_SERVER_URL}/${TESTSUITE_REPO} ${TESTSUITE_DIR}
+          git config --global --add safe.directory ${TESTSUITE_DIR}
+
+          echo ${GATETEST_COMMAND} > /tmp/test_commands.json
+          TEST_NAME=$(jq -j '.name' /tmp/test_commands.json)
+          TEST_OPTIONS=$(jq -j '.options' /tmp/test_commands.json)
+          TEST_TIMEOUT=$(jq -j '.timeout' /tmp/test_commands.json)
+          TEST_CMD=$(jq -j '.testcmd' /tmp/test_commands.json)
+          TEST_DIR=$(jq -j '.dir' /tmp/test_commands.json)
+
+          cd ${TESTSUITE_DIR}
+
+          if [[ "${TESTSUITE_TEST_PR}" =~ [0-9]+ ]] ; then
+          	echo "Checking out testsuite PR ${TESTSUITE_TEST_PR}"
+          	gh pr checkout "${TESTSUITE_TEST_PR}" -b "pr-${TESTSUITE_TEST_PR}" || \
+          		{ echo "::error::Testsuite PR ${TESTSUITE_TEST_PR} not found" ; exit 1 ; }
+          	git --no-pager log -1 --oneline
+          fi
+
+          TESTRC=0
+          ${SCRIPT_DIR}/runAsteriskGateTests.sh \
+            --test-timeout=${TEST_TIMEOUT} \
+            --testsuite-command="${TEST_OPTIONS} ${TEST_CMD}" || TESTRC=1
+          exit $TESTRC
  
       - name: Save Output
         id: save-output
@@ -102,5 +123,4 @@ jobs:
           name: ${{env.GC_TEST_NAME}}
           path: |
             ${{env.GC_TESTSUITE_DIR}}/logs
-            ${{inputs.cache_dir}}
 
